apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ejemplo-db
  SPRING_DATASOURCE_USERNAME: usuario
  SPRING_DATASOURCE_PASSWORD: usuario123
---
# Opcional: variables para frontend si hiciera falta en el futuro
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NGINX_WORKER_PROCESSES: "auto"

